=== euroahmed/Chansonnier/chansonnier/org.eclipse.smila.processing.bpel.test/configuration/org.eclipse.smila.processing.bpel/pipelines/id.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <!--
        Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. All rights reserved. This program and the
        accompanying materials are made available under the terms of the Eclipse Public License v1.0 which accompanies
        this distribution, and is available at http://www.eclipse.org/legal/epl-v10.html 
        Contributors: Juergen Schumacher (empolis GmbH) - initial design
    -->
<schema targetNamespace="http://www.eclipse.org/smila/id" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:id="http://www.eclipse.org/smila/id"
    elementFormDefault="qualified">

    <annotation>
        <documentation>
            http://wiki.eclipse.org/SMILA/Project_Concepts/ID_Concept
		</documentation>
    </annotation>

    <element name="IdList" type="id:IdListType" />

    <complexType name="IdListType">
        <sequence maxOccurs="1" minOccurs="1">
            <element ref="id:Id" maxOccurs="unbounded" minOccurs="0" />
        </sequence>
    </complexType>

    <element name="Id" type="id:IdType" />

    <complexType name="IdType">
        <sequence maxOccurs="1" minOccurs="1">
            <element name="Source" type="string" />
            <element ref="id:Key" minOccurs="1" maxOccurs="unbounded" />
            <element ref="id:Element" minOccurs="0" maxOccurs="1" />
            <element name="Fragment" type="string" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="version" type="string" use="required" />
    </complexType>

    <element name="Key">
        <complexType>
            <simpleContent>
                <extension base="string">
                    <attribute name="name" type="string" use="optional" />
                </extension>
            </simpleContent>
        </complexType>
    </element>

    <element name="Element">
        <complexType>
            <sequence maxOccurs="1" minOccurs="1">
                <element ref="id:Key" minOccurs="1" maxOccurs="unbounded" />
                <element ref="id:Element" minOccurs="0" maxOccurs="1" />
            </sequence>
        </complexType>
    </element>

</schema>

=== euroahmed/Chansonnier/chansonnier/org.eclipse.smila.datamodel/xml/id-list-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Juergen Schumacher (empolis GmbH) - initial example
-->
<IdList xmlns="http://www.eclipse.org/smila/id" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.eclipse.org/smila/id id.xsd ">
	<Id version="1.0">
		<Source>share</Source>
		<Key>PDF/big.pdf</Key>
	</Id>

	<Id version="1.0">
		<Source>share</Source>
		<Key>PDF/big.pdf</Key>
		<Fragment>0</Fragment><!-- or start counting at 1? -->
	</Id>

	<Id version="1.0">
		<Source>share</Source>
		<Key>Archive/oldstuff.zip</Key>
	</Id>

	<Id version="1.0">
		<Source>share</Source>
		<Key>Archive/oldstuff.zip</Key>
		<Element>
			<Key>PDF/old.pdf</Key>
		</Element>
	</Id>

	<Id version="1.0">
		<Source>share</Source>
		<Key>Archive/oldstuff.zip</Key>
		<Element>
			<Key>PDF/old.pdf</Key>
		</Element>
		<Fragment>0</Fragment>
	</Id>

	<Id version="1.0">
		<Source>share</Source>
		<Key>Archive/oldstuff.zip</Key>
		<Element>
			<Key>another.zip</Key>
			<Element>
				<Key>another.pdf</Key>
			</Element>
		</Element>
		<Fragment>0</Fragment>
	</Id>

	<Id version="1.0">
		<Source>mail</Source>
		<Key>INBOX/42</Key>
		<Element>
			<Key>2</Key>
		</Element>
	</Id>

	<Id version="1.0">
		<Source>db</Source>
		<Key name="x">0815</Key>
		<Key name="y">4711</Key>
	</Id>
</IdList>
